name: tests-automatises-testrail
on: [workflow_dispatch]

jobs:
  envoyer-resultats-testrail:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v3
        
      - name: Configuration Python
        if: always()
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
          
      - name: Installation et exécution TestRail CLI
        if: always()
        env:
          TESTRAIL_HOST: ${{ secrets.TESTRAIL_HOST }}
          TESTRAIL_PROJECT: ${{ secrets.TESTRAIL_PROJECT }}
          TESTRAIL_USERNAME: ${{ secrets.TESTRAIL_USERNAME }}
          TESTRAIL_PASSWORD: ${{ secrets.TESTRAIL_PASSWORD }}
        run: |
          pip install trcli
          trcli -y \
            -h "$TESTRAIL_HOST" \
            --project "$TESTRAIL_PROJECT" \
            -u "$TESTRAIL_USERNAME" \
            -p "$TESTRAIL_PASSWORD" \
            parse_junit \
            --title "Tests Automatisés GitHub Actions" \
            --run-description ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} \
            -f "reports/junit*.xml"
